"""<fixed vers>

Revision ID: c2425387ccdb
Revises: 2f6aa38f9289
Create Date: 2024-03-02 18:02:34.492544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2425387ccdb'
down_revision = '2f6aa38f9289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('activity_subject_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_id'], ['id'])
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activity_subject_fkey', 'subject', ['subject'], ['id'])
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
